### ISSUE TITLE
Installing noise-free-cnv-filter on CentOS cluster

### ISSUE THREAD

**Issue by anlo328** [ginsbach/noise-free-cnv#1]
Dear Philip / noise-free-cnv team,

I'm working with about 1000 SNP6.0-assayed tumor (cell line) samples that are presumptively quite noisy, mainly because there are no normal samples for reference. I'm aiming to see how well noise-free-cnv-filter can help me with this issue. 

Since my dataset size and expected workload are quite big, I need to run the program on the computing cluster which is provided to me, which is CentOS 7.8. Trying to "make" the cloned git repo gives the following error:

```
Package gtkmm-2.4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtkmm-2.4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtkmm-2.4' found
Package fftw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `fftw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fftw3' found
g++ -o src/CnvCalling.o src/CnvCalling.cc -c -Wall -O3  -DNFCNV_VERSION_MAJOR=1 -DNFCNV_VERSION_MINOR=13 -DNFCNV_SHARE_FOLDER='"share/noise-free-cnv/"'
In file included from src/CnvSequence.hh:22:0,
                 from src/CnvCalling.hh:23,
                 from src/CnvCalling.cc:20:
src/CnvStringPool.hh:25:20: fatal error: glibmm.h: No such file or directory
 #include <glibmm.h>
                    ^
compilation terminated.
make: *** [src/CnvCalling.o] Error 1
```

After consulting with my IT support, the issue seems to be that one of the dependencies is gtk4, while on our cluster the version is gtk3 unfortunately. They have said that the only solution they see is the (unlikely) case that you would be able to provide a binary for CentOS 7.8. Can you do this by any chance, or do you see any other solutions for me to get noise-free-cnv-filter running?

Any advice would be highly appreciated. 

Best wishes,
Andreas

**Comment by ginsbach** [comment]
Thank you for your interest in noise-free-cnv!
I'm unable to provide CentOS 7.8 binaries, but have successfully used the Wine compatibility layer to execute the [Windows zip archive version](https://github.com/ginsbach/noise-free-cnv/blob/main/distribute/noise-free-cnv_2.2-1_win64.zip) on different distributions. Perhaps that might work for you?

Note that noise-free-cnv-gtk (i.e. the editor for interactive visualization and manipulation) is still in active use, but noise-free-cnv-filter has not been maintained for many years. All the examples on https://ginsbach.github.io/noise-free-cnv/ are using noise-free-cnv-gtk.

**Comment by anlo328** [comment]
Thanks a lot for the swift answer Philip! I'm afraid using Wine won't be possible on the cluster unfortunately. Maybe I can try to use the Win version on my home PC, do you think a standard PC could handle noise-free-cnv-filter for about 1000 logR files from SNP6.0?
